services:
  # Backend API Service
  - type: web
    name: meeting-intelligence-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        value: sqlite:///./meetings.db
      - key: UPLOAD_DIR
        value: ./uploads
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: meeting-data
      mountPath: /opt/render/project/src/backend
      sizeGB: 1
